### ISSUE TITLE
Support Scala 2.12

### ISSUE THREAD

**Issue by rubaimushtaq** [pityka/nspl#1]

**Comment by pityka** [comment]
I updated the build and published artifacts against 2.12.1. https://github.com/pityka/nspl/commit/a96666e8d29d06a68a192d02374cb05782dd3d7d

**Comment by mredaelli** [comment]
I think there are some issues with the repository, at least for core:
https://mvnrepository.com/artifact/io.github.pityka/nspl-core_2.12/0.0.17

**Comment by pityka** [comment]
Thank you for reporting. I published it to sonatype. I hope it will sync to maven central soon.
https://oss.sonatype.org/service/local/repositories/releases/content/io/github/pityka/nspl-core_2.12/0.0.17/nspl-core_2.12-0.0.17.jar

**Comment by mredaelli** [comment]
Thanks!

I added

> val nsplVersion = "0.0.17"
> 
> resolvers ++= Seq(
>   Resolver.sonatypeRepo("public")
> )
> 
> libraryDependencies  ++= Seq(
>   "io.github.pityka" %% "nspl-awt" % nsplVersion
> )

but now I get

> [error] (*:ssExtractProject) sbt.ResolveException: unresolved dependency: io.github.pityka#nspl-shared-jvm_2.12;0.0.17: not found

**Comment by esamson** [comment]
I also get the same error. `nspl-shared-jvm_2.12` is not available in maven central.

http://search.maven.org/#search%7Cga%7C1%7Cnspl-shared-jvm

**Comment by pityka** [comment]
Will try to figure this out. There are some sub projects in the build which have 2.11 dependencies. 

In the meantime, please try publishing it into your local ivy. This is the way I am using it as well.

**Comment by pityka** [comment]
Published builds for 2.12 to maven central. 
e.g. https://repo1.maven.org/maven2/io/github/pityka/nspl-shared-jvm_2.12/

The "nspl-saddle" artifact depends on a fork of saddle which is cross built (and published) to 2.12.

**Comment by pityka** [comment]
A simple sbt file with contents `libraryDependencies += "io.github.pityka" %% "nspl-awt" % "0.0.19"` can resolve now both on 2.11 and 2.12.
